services:
  postgres:
    image: postgres:16-alpine
    container_name: tariff_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres12
      POSTGRES_DB: TariffDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TariffDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: tariffcalculator_api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=TariffDb;Username=postgres;Password=postgres12
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: